# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\demo\jiuyin_robot\qt_ui\actvip.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ActVipForm(object):
    def setupUi(self, ActVipForm):
        ActVipForm.setObjectName("ActVipForm")
        ActVipForm.resize(400, 200)
        self.gridLayout = QtWidgets.QGridLayout(ActVipForm)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_act = QtWidgets.QPushButton(ActVipForm)
        self.bt_act.setObjectName("bt_act")
        self.gridLayout.addWidget(self.bt_act, 3, 0, 1, 1)
        self.le_act_code = QtWidgets.QLineEdit(ActVipForm)
        self.le_act_code.setObjectName("le_act_code")
        self.gridLayout.addWidget(self.le_act_code, 1, 0, 1, 1)
        self.lb_log = QtWidgets.QLabel(ActVipForm)
        self.lb_log.setText("")
        self.lb_log.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_log.setObjectName("lb_log")
        self.gridLayout.addWidget(self.lb_log, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ActVipForm)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.retranslateUi(ActVipForm)
        QtCore.QMetaObject.connectSlotsByName(ActVipForm)

    def retranslateUi(self, ActVipForm):
        _translate = QtCore.QCoreApplication.translate
        ActVipForm.setWindowTitle(_translate("ActVipForm", "激活vip"))
        self.bt_act.setText(_translate("ActVipForm", "确定"))
        self.label_2.setText(_translate("ActVipForm", "请输入32位激活码"))
