# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\project\python\jiuyin_robot\qt_ui\caiji.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaiJiForm(object):
    def setupUi(self, CaiJiForm):
        CaiJiForm.setObjectName("CaiJiForm")
        CaiJiForm.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(CaiJiForm)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(CaiJiForm)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(CaiJiForm)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 0, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(CaiJiForm)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(CaiJiForm)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)

        self.retranslateUi(CaiJiForm)
        QtCore.QMetaObject.connectSlotsByName(CaiJiForm)

    def retranslateUi(self, CaiJiForm):
        _translate = QtCore.QCoreApplication.translate
        CaiJiForm.setWindowTitle(_translate("CaiJiForm", "采集设置"))
        self.checkBox.setText(_translate("CaiJiForm", "铅矿"))
        self.checkBox_2.setText(_translate("CaiJiForm", "铜矿"))
        self.checkBox_3.setText(_translate("CaiJiForm", "白杨树"))
        self.pushButton.setText(_translate("CaiJiForm", "确定"))
