# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\demo\jiuyin_robot\qt_ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(463, 339)
        self.verticalLayout = QtWidgets.QVBoxLayout(main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_user_name = QtWidgets.QLabel(main)
        self.lb_user_name.setObjectName("lb_user_name")
        self.horizontalLayout.addWidget(self.lb_user_name)
        self.lb_user_vip = QtWidgets.QLabel(main)
        self.lb_user_vip.setObjectName("lb_user_vip")
        self.horizontalLayout.addWidget(self.lb_user_vip)
        self.lb_q_qun = QtWidgets.QLabel(main)
        self.lb_q_qun.setObjectName("lb_q_qun")
        self.horizontalLayout.addWidget(self.lb_q_qun)
        self.bt_chongzhi = QtWidgets.QPushButton(main)
        self.bt_chongzhi.setObjectName("bt_chongzhi")
        self.horizontalLayout.addWidget(self.bt_chongzhi)
        self.bt_ws_con = QtWidgets.QPushButton(main)
        self.bt_ws_con.setObjectName("bt_ws_con")
        self.horizontalLayout.addWidget(self.bt_ws_con)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(main)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setEnabled(True)
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.bt_start_up = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.bt_start_up.setGeometry(QtCore.QRect(340, 100, 75, 31))
        self.bt_start_up.setObjectName("bt_start_up")
        self.cb_tuanlian = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.cb_tuanlian.setGeometry(QtCore.QRect(10, 10, 101, 31))
        self.cb_tuanlian.setObjectName("cb_tuanlian")
        self.cb_neigong = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.cb_neigong.setGeometry(QtCore.QRect(110, 10, 91, 31))
        self.cb_neigong.setObjectName("cb_neigong")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.lb_log = QtWidgets.QLabel(main)
        self.lb_log.setObjectName("lb_log")
        self.verticalLayout.addWidget(self.lb_log)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 4)

        self.retranslateUi(main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "设置"))
        self.lb_user_name.setText(_translate("main", "用户名"))
        self.lb_user_vip.setText(_translate("main", "vip"))
        self.lb_q_qun.setText(_translate("main", "qq群：978098280"))
        self.bt_chongzhi.setText(_translate("main", "赞助"))
        self.bt_ws_con.setText(_translate("main", "连接到服务器"))
        self.bt_start_up.setText(_translate("main", "启动"))
        self.cb_tuanlian.setText(_translate("main", "自动团练授业"))
        self.cb_neigong.setText(_translate("main", "自动点内功"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("main", "基本设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("main", "刺探设置"))
        self.lb_log.setText(_translate("main", "运行日志"))
